<?php
/**
 * Author: Darcey Lloyd
 * Email: Darcey@AllForTheCode.co.uk
 * Date: 10/2015
 */

use AFTC\Framework\Core\Router as Router;

/**
 * USAGE:
 * $param1 = url
 * $param2 = controller file name
 * $param3 = controller function name (blank will default call the function "init" if it exists)
 * $param4 = cache (true||false)
 *
 * NOTE ON CACHE:
 * Page cache files are generated by controller + function ($param2 + $param3) allows multiple
 * this allows for multiple cache files to be created and used from a single controller that
 * can have multiple outputs
 */

Router::addRoute("","login","",false);
Router::addRoute("login","login","",false);
Router::addRoute("logout","logout","",false);
Router::addRoute("access_denied","access_denied","",false);
Router::addRoute("home","home","",false);

Router::addRoute("products/red car","products/index","",false);
Router::addRoute("products/red_car","products/index","",false);
Router::addRoute("products/red-car","products/index","",false);
Router::addRoute("products/redcar","products/index","",false);