<?php
/**
 * Author: Darcey Lloyd
 * Email: Darcey@AllForTheCode.co.uk
 * Date: 10/2015
 */

use AFTC\Framework\Core\Router as Router;

/**
 * USAGE:
 * $param1 = url
 * $param2 = controller namespace. NOTE: No need to enter "AFTC\\Framework\\App\\Conrollers\\", should reflect dir structure eg "Products\\Promo1"
 * $param3 = controller function to call (blank is fine if you want to process everything from the "controller file name" aka $param2
 * $param4 = cache (true||false)
 *
 * NOTE ON CACHE:
 * Page cache files are generated by controller + function ($param2 + $param3) allows multiple
 * this allows for multiple cache files to be created and used from a single controller that
 * can have multiple outputs
 */

Router::addRoute("","login","",false);
Router::addRoute("moo","login","",false);
Router::addRoute("login","login","",false);

Router::addRoute("products/test","Products\\Promo1","",false);
Router::addRoute("products/promo1","Products\\Promo1","",false);


Router::addRoute("logout","logout","",false);
Router::addRoute("access_denied","access_denied","",false);
Router::addRoute("home","home","",false);
Router::addRoute("bootstrap","bootstrap","",false);
Router::addRoute("usage_examples","usage_examples","",false);

Router::addRoute("products/red car","products/index","",false);
Router::addRoute("products/red_car","products/index","",false);
Router::addRoute("products/red-car","products/index","",false);
Router::addRoute("products/redcar","products/index","",false);